### ISSUE TITLE
Dancing Noalf's image background is white 

### ISSUE THREAD

**Issue by Shohei-Yamamoto** [uhooi/UhooiPicBook#106]
noalfのdancingの画像の背景が透過でないことに気付きました。全部は見ていないですが、他のモンスターは大丈夫そうです。

<img src="https://user-images.githubusercontent.com/31381763/95017826-95062100-0696-11eb-935a-6462deb0070c.jpeg" width=300>

**Comment by uhooi** [comment]
Issue報告ありがとうございますー！
ホントですね、ライトモードで使うことが多かったので気づきませんでした、、
もうすぐモンスターの追加対応を行う予定なので、同時に修正も行いますね！

**Comment by uhooi** [comment]
全モンスターを確認しました、noalfのみ背景色が透過でなく白でした。

**Comment by Shohei-Yamamoto** [comment]
夜はダークモードになるのでたまたま気付きました！^^

**Comment by uhooi** [comment]
@Shohei-Yamamoto 先にnoalfのダンシングイメージを修正しました！
ご確認お願いします 🙇

**Comment by Shohei-Yamamoto** [comment]
noalf確認しました！　
新キャラ意外性ありますねw

**Comment by uhooi** [comment]
ご確認ありがとうございます！
意外性ワロタｗ
