### ISSUE TITLE
Can not make setup 

### ISSUE THREAD

**Issue by M1zz** [uhooi/UhooiPicBook#115]
xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve Carthage 0.36.0 with SPM
make[1]: *** [install-mint] Error 1
make: *** [setup] Error 2

**Comment by uhooi** [comment]
I'll check.
One moment, please.

**Comment by uhooi** [comment]
@M1zz 
If you don't have Xcode 12 installed, please install it.
After run `export DEVELOPER_DIR {Xcode 12 path}` , run `make setup` again.

```
# Replace the Xcode path with your actual path.
$ export DEVELOPER_DIR=/Applications/Xcode_12.app
$ make setup
```
