### ISSUE TITLE
GitHub doesn't recognize the license as MIT

### ISSUE THREAD

**Issue by uhooi** [uhooi/UhooiPicBook#117]
## Screenshots

|GitHub|Badge|
|:--|:--|
|![スクリーンショット_2020-11-18_15_03_41](https://user-images.githubusercontent.com/21194714/99491644-77bfb480-29af-11eb-921d-37ba9837a521.png)|![スクリーンショット_2020-11-18_15_03_29](https://user-images.githubusercontent.com/21194714/99491698-8d34de80-29af-11eb-9ab6-33d822a8d310.png)|

## References

- https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#searching-github-by-license-type
- https://github.com/mono0926/LicensePlist#--config-path
- https://twitter.com/the_uhooi/status/1314022364003274752?s=20

**Comment by myihsan** [comment]
#113 seems to be the reason.
Rename that file or place it into a folder may solve this issue.

**Comment by uhooi** [comment]
Thanks for advice :)
I'll modify it for your advice.

**Comment by uhooi** [comment]
I'll stay open until I'm sure it's fixed.

**Comment by uhooi** [comment]
I deleted `license_plist.yml` and it fixed the problem.
This issue is closed.
