### ISSUE TITLE
Bump actions/checkout to v3

### ISSUE THREAD

**Issue by uhooi** [uhooi/UhooiPicBook#321]
## References

- https://github.com/actions/checkout/releases/tag/v3.0.0
- https://twitter.com/the_uhooi/status/1498802416833396736

**Comment by RishiKumarRay** [comment]
do we have to simply change to v3?

**Comment by uhooi** [comment]
@RishiKumarRay 
Yes.
Is there a problem?

**Comment by RishiKumarRay** [comment]
@uhooi it looks easy so that's why i asked , can i go for PR? @uhooi

**Comment by uhooi** [comment]
@RishiKumarRay OK, thx!!

**Comment by RishiKumarRay** [comment]
@uhooi please review
